import uuid
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session

from app.db.models.user import User
from app.db.models.visit import Visit
from app.db.session import get_db
from app.schemas.visit import VisitCreate

router = APIRouter()


@router.post("/visits", response_model=dict)
def create_visit(request: Request, visit_data: VisitCreate, db: Session = Depends(get_db)):
    """
    Creates a new visit with status='pending'.
    Returns the created visit_id.
    """
    clerk_id = getattr(request.state, "clerk_user_id", None)
    if not clerk_id:
        raise HTTPException(
            status_code=401, detail={"error": {"code": "UNAUTHORIZED"}}
        )

    # Lookup user from DB, since user_id FK is required
    user = db.query(User).filter(User.clerk_user_id == clerk_id).first()
    if not user:
        raise HTTPException(
            status_code=401, detail={"error": {"code": "UNAUTHORIZED"}}
        )

    # Create visit
    visit = Visit(
        id=uuid.uuid4(),
        user_id=user.id,
        title=visit_data.title,
        visit_date=visit_data.visit_date,
        doctor_name=visit_data.doctor_name,
        consent_at=visit_data.consent_at
    )
    db.add(visit)
    db.commit()
    db.refresh(visit)

    return {"visit_id": visit.id}


@router.get("/visits", response_model=list)
def list_visits(request: Request, db: Session = Depends(get_db)):
    """
    Lists all visits belonging to the current authenticated user.
    """
    clerk_id = getattr(request.state, "clerk_user_id", None)
    if not clerk_id:
        raise HTTPException(status_code=401, detail="Unauthorized")

    user = db.query(User).filter(User.clerk_user_id == clerk_id).first()
    if not user:
        raise HTTPException(status_code=401, detail="Unauthorized")

    visits = db.query(Visit).filter(Visit.user_id == user.id).order_by(Visit.visit_date.desc()).all()
    
    return [{
        "id": str(v.id),
        "title": v.title,
        "visit_date": v.visit_date.isoformat() if v.visit_date else None,
        "doctor_name": v.doctor_name,
        "status": v.status.value,
        "audio_s3_key": v.audio_s3_key
    } for v in visits]


@router.get("/visits/{visit_id}", response_model=dict)
def get_visit_detail(visit_id: uuid.UUID, request: Request, db: Session = Depends(get_db)):
    """
    Returns single visit row including status.
    """
    clerk_id = getattr(request.state, "clerk_user_id", None)
    user = db.query(User).filter(User.clerk_user_id == clerk_id).first()
    if not user:
        raise HTTPException(status_code=401, detail="Unauthorized")

    visit = db.query(Visit).filter(Visit.id == visit_id, Visit.user_id == user.id).first()
    if not visit:
        raise HTTPException(status_code=404, detail="Visit not found")

    return {
        "id": str(visit.id),
        "title": visit.title,
        "visit_date": visit.visit_date.isoformat() if visit.visit_date else None,
        "doctor_name": visit.doctor_name,
        "status": visit.status.value,
        "audio_s3_key": visit.audio_s3_key,
        "tags": visit.tags
    }


@router.get("/visits/{visit_id}/transcript", response_model=dict)
def get_visit_transcript(visit_id: uuid.UUID, request: Request, db: Session = Depends(get_db)):
    """
    Fetches the AI-generated transcript string.
    """
    from app.db.models.transcript import Transcript
    # check ownership or similar loop loads
    transcript = db.query(Transcript).filter(Transcript.visit_id == visit_id).first()
    if not transcript:
         raise HTTPException(status_code=404, detail="Transcript not ready or not found")

    return {
         "raw_text": transcript.raw_text,
         "chunks": transcript.chunks,
         "language_detected": transcript.language_detected
    }


@router.get("/visits/{visit_id}/summary", response_model=dict)
def get_visit_summary(visit_id: uuid.UUID, request: Request, db: Session = Depends(get_db)):
    """
    Fetches structured SOAP Diagnostics generated by LLMs.
    """
    from app.db.models.summary import Summary
    summary = db.query(Summary).filter(Summary.visit_id == visit_id).first()
    if not summary:
         raise HTTPException(status_code=404, detail="Summary not ready or not found")

    return {
         "overview": summary.overview,
         "medications": summary.medications,
         "diagnoses": summary.diagnoses,
         "action_items": summary.action_items,
         "urgency_tag": summary.urgency_tag.value if summary.urgency_tag else "normal"
    }
